export const cardFiles = 
{
    
    AceOfHearts: require('../images/Cards/AceOfHearts.svg'),
    TwoOfHearts: require('../images/Cards/TwoOfHearts.svg'),
    ThreeOfHearts: require('../images/Cards/ThreeOfHearts.svg'),
    FourOfHearts: require('../images/Cards/FourOfHearts.svg'),
    FiveOfHearts: require('../images/Cards/FiveOfHearts.svg'),
    SixOfHearts: require('../images/Cards/SixOfHearts.svg'),
    SevenOfHearts: require('../images/Cards/SevenOfHearts.svg'),
    EightOfHearts: require('../images/Cards/EightOfHearts.svg'),
    NineOfHearts: require('../images/Cards/NineOfHearts.svg'),
    TenOfHearts: require('../images/Cards/TenOfHearts.svg'),
    JackOfHearts: require('../images/Cards/JackOfHearts.svg'),
    QueenOfHearts: require('../images/Cards/QueenOfHearts.svg'),
    KingOfHearts: require('../images/Cards/KingOfHearts.svg'),
    AceOfDiamonds: require('../images/Cards/AceOfDiamonds.svg'),
    TwoOfDiamonds: require('../images/Cards/TwoOfDiamonds.svg'),
    ThreeOfDiamonds: require('../images/Cards/ThreeOfDiamonds.svg'),
    FourOfDiamonds: require('../images/Cards/FourOfDiamonds.svg'),
    FiveOfDiamonds: require('../images/Cards/FiveOfDiamonds.svg'),
    SixOfDiamonds: require('../images/Cards/SixOfDiamonds.svg'),
    SevenOfDiamonds: require('../images/Cards/SevenOfDiamonds.svg'),
    EightOfDiamonds: require('../images/Cards/EightOfDiamonds.svg'),
    NineOfDiamonds: require('../images/Cards/NineOfDiamonds.svg'),
    TenOfDiamonds: require('../images/Cards/TenOfDiamonds.svg'),
    JackOfDiamonds: require('../images/Cards/JackOfDiamonds.svg'),
    QueenOfDiamonds: require('../images/Cards/QueenOfDiamonds.svg'),
    KingOfDiamonds: require('../images/Cards/KingOfDiamonds.svg'),
    AceOfClubs: require('../images/Cards/AceOfClubs.svg'),
    TwoOfClubs: require('../images/Cards/TwoOfClubs.svg'),
    ThreeOfClubs: require('../images/Cards/ThreeOfClubs.svg'),
    FourOfClubs: require('../images/Cards/FourOfClubs.svg'),
    FiveOfClubs: require('../images/Cards/FiveOfClubs.svg'),
    SixOfClubs: require('../images/Cards/SixOfClubs.svg'),
    SevenOfClubs: require('../images/Cards/SevenOfClubs.svg'),
    EightOfClubs: require('../images/Cards/EightOfClubs.svg'),
    NineOfClubs: require('../images/Cards/NineOfClubs.svg'),
    TenOfClubs: require('../images/Cards/TenOfClubs.svg'),
    JackOfClubs: require('../images/Cards/JackOfClubs.svg'),
    QueenOfClubs: require('../images/Cards/QueenOfClubs.svg'),
    KingOfClubs: require('../images/Cards/KingOfClubs.svg'),
    AceOfSpades: require('../images/Cards/AceOfSpades.svg'),
    TwoOfSpades: require('../images/Cards/TwoOfSpades.svg'),
    ThreeOfSpades: require('../images/Cards/ThreeOfSpades.svg'),
    FourOfSpades: require('../images/Cards/FourOfSpades.svg'),
    FiveOfSpades: require('../images/Cards/FiveOfSpades.svg'),
    SixOfSpades: require('../images/Cards/SixOfSpades.svg'),
    SevenOfSpades: require('../images/Cards/SevenOfSpades.svg'),
    EightOfSpades: require('../images/Cards/EightOfSpades.svg'),
    NineOfSpades: require('../images/Cards/NineOfSpades.svg'),
    TenOfSpades: require('../images/Cards/TenOfSpades.svg'),
    JackOfSpades: require('../images/Cards/JackOfSpades.svg'),
    QueenOfSpades: require('../images/Cards/QueenOfSpades.svg'),
    KingOfSpades: require('../images/Cards/KingOfSpades.svg'),
    BackOfCard: require('../images/Cards/BackOfCard.svg'),
    ErrorCard: require('../images/Cards/error.png')
}

export default cardFiles;